spring.application.name=piraozada

spring.datasource.url=jdbc:postgresql://localhost:2714/piraozada
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update