spring.application.name=piraozada

spring.datasource.url=jdbc:postgresql://localhost:1603/piraozada
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=piraozada-chave-super-secreta-2024-mundo-novo-ba
